version: '3.7'

services:
  # База данных
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: smarta_mintrud_courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
  # PHP сервер
  php:
    build:
      context: .
      dockerfile: dockerfile.php
    container_name: mintrud-courses-php
    working_dir: /var/www/html
    volumes:
      - ./server:/var/www/html
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: smarta_mintrud_courses
    depends_on:
      - postgres
    networks:
      - app-network

  # NGINX сервер
  nginx:
    image: nginx
    container_name: mintrud-courses-nginx
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  
  # NodeJS для Vite
  node:
    image: node:lts-alpine
    container_name: mintrud-courses-node
    working_dir: /app
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    stdin_open: true
    tty: true
    depends_on:
      - nginx
    networks:
      - app-network
volumes:
  postgres_data:
  node_modules:

networks:
  app-network:
    driver: bridge